### PR TITLE
Analytics Update

### PR DESCRIPTION
**Pull request by iamonuwa**
@villanuevawill please review. #2

### CODE REVIEW

**Comment by villanuevawill** [comment]
Thanks - I'll go ahead and test this today.

**Comment by iamonuwa** [comment]
Thank you

**Comment by iamonuwa** [comment]
@villanuevawill, please review

**Comment by villanuevawill** [comment]
@iamonuwa it looks like that solves it... but the original writeup requested more:
`Update end date to be locked through UTC time. At this point, it just locks to the computers' timezone. Also, clearly state that times are based on UTC.`

There is no UTC label anywhere.

**Comment by iamonuwa** [comment]
I'll update that right now.

Thank you

**Comment by iamonuwa** [comment]
@villanuevawill by locking, you mean displaying the current date in UTC format?

**Comment by iamonuwa** [comment]
Alright, I get it now loud and clear. Thank you

**Comment by iamonuwa** [comment]
@villanuevawill please review

**Pull request merged**
